# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyAlgGui.ui'
#
# Created: Fri Apr 23 20:34:43 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 667)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.horizontalLayout.addWidget(self.webView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 25))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.algDockWidget = QtGui.QDockWidget(MainWindow)
        self.algDockWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algDockWidget.sizePolicy().hasHeightForWidth())
        self.algDockWidget.setSizePolicy(sizePolicy)
        self.algDockWidget.setFloating(False)
        self.algDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.algDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.algDockWidget.setObjectName("algDockWidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algTree = QtGui.QTreeWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algTree.sizePolicy().hasHeightForWidth())
        self.algTree.setSizePolicy(sizePolicy)
        self.algTree.setObjectName("algTree")
        item_0 = QtGui.QTreeWidgetItem(self.algTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.algTree.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.algTree)
        self.algDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.algDockWidget)
        self.algOptionsDockWidget = QtGui.QDockWidget(MainWindow)
        self.algOptionsDockWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algOptionsDockWidget.sizePolicy().hasHeightForWidth())
        self.algOptionsDockWidget.setSizePolicy(sizePolicy)
        self.algOptionsDockWidget.setMinimumSize(QtCore.QSize(274, 248))
        self.algOptionsDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.algOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.algOptionsDockWidget.setObjectName("algOptionsDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setBaseSize(QtCore.QSize(0, 230))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listSettingsGroupBox = QtGui.QGroupBox(self.frame)
        self.listSettingsGroupBox.setGeometry(QtCore.QRect(10, 70, 241, 131))
        self.listSettingsGroupBox.setObjectName("listSettingsGroupBox")
        self.listSizeBox = QtGui.QSpinBox(self.listSettingsGroupBox)
        self.listSizeBox.setGeometry(QtCore.QRect(4, 20, 71, 28))
        self.listSizeBox.setMinimum(1)
        self.listSizeBox.setMaximum(1000)
        self.listSizeBox.setProperty("value", 10)
        self.listSizeBox.setObjectName("listSizeBox")
        self.listLBoundBox = QtGui.QSpinBox(self.listSettingsGroupBox)
        self.listLBoundBox.setGeometry(QtCore.QRect(4, 60, 71, 28))
        self.listLBoundBox.setMinimum(-1000)
        self.listLBoundBox.setMaximum(1000)
        self.listLBoundBox.setObjectName("listLBoundBox")
        self.listUBoundBox = QtGui.QSpinBox(self.listSettingsGroupBox)
        self.listUBoundBox.setGeometry(QtCore.QRect(4, 100, 71, 28))
        self.listUBoundBox.setMaximum(1000)
        self.listUBoundBox.setProperty("value", 1000)
        self.listUBoundBox.setObjectName("listUBoundBox")
        self.listLBoundLabel = QtGui.QLabel(self.listSettingsGroupBox)
        self.listLBoundLabel.setGeometry(QtCore.QRect(90, 65, 91, 18))
        self.listLBoundLabel.setObjectName("listLBoundLabel")
        self.listUBoundLabel = QtGui.QLabel(self.listSettingsGroupBox)
        self.listUBoundLabel.setGeometry(QtCore.QRect(90, 105, 91, 18))
        self.listUBoundLabel.setObjectName("listUBoundLabel")
        self.listInputLineEdit = QtGui.QLineEdit(self.frame)
        self.listInputLineEdit.setEnabled(True)
        self.listInputLineEdit.setGeometry(QtCore.QRect(4, 91, 231, 26))
        self.listInputLineEdit.setObjectName("listInputLineEdit")
        self.listSortButton = QtGui.QPushButton(self.frame)
        self.listSortButton.setGeometry(QtCore.QRect(162, 7, 92, 28))
        self.listSortButton.setObjectName("listSortButton")
        self.listInputRadioButton = QtGui.QRadioButton(self.frame)
        self.listInputRadioButton.setGeometry(QtCore.QRect(4, 22, 108, 23))
        self.listInputRadioButton.setObjectName("listInputRadioButton")
        self.listGenRadioButton = QtGui.QRadioButton(self.frame)
        self.listGenRadioButton.setGeometry(QtCore.QRect(4, 44, 111, 23))
        self.listGenRadioButton.setObjectName("listGenRadioButton")
        self.horizontalLayout_2.addWidget(self.frame)
        self.algOptionsDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.algOptionsDockWidget)
        self.newAlgDockWidget = QtGui.QDockWidget(MainWindow)
        self.newAlgDockWidget.setMinimumSize(QtCore.QSize(288, 619))
        self.newAlgDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.newAlgDockWidget.setObjectName("newAlgDockWidget")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents_3)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pathLabel = QtGui.QLabel(self.frame_2)
        self.pathLabel.setGeometry(QtCore.QRect(10, 10, 61, 18))
        self.pathLabel.setObjectName("pathLabel")
        self.pathLineEdit = QtGui.QLineEdit(self.frame_2)
        self.pathLineEdit.setGeometry(QtCore.QRect(10, 30, 161, 26))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.pathBrowseButton = QtGui.QPushButton(self.frame_2)
        self.pathBrowseButton.setGeometry(QtCore.QRect(175, 30, 26, 26))
        self.pathBrowseButton.setObjectName("pathBrowseButton")
        self.newAlgPropGroupBox = QtGui.QGroupBox(self.frame_2)
        self.newAlgPropGroupBox.setGeometry(QtCore.QRect(10, 70, 271, 491))
        self.newAlgPropGroupBox.setObjectName("newAlgPropGroupBox")
        self.newAlgFuncLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgFuncLabel.setGeometry(QtCore.QRect(0, 10, 171, 18))
        self.newAlgFuncLabel.setObjectName("newAlgFuncLabel")
        self.newAlgFuncComboBox = QtGui.QComboBox(self.newAlgPropGroupBox)
        self.newAlgFuncComboBox.setGeometry(QtCore.QRect(0, 30, 191, 27))
        self.newAlgFuncComboBox.setObjectName("newAlgFuncComboBox")
        self.newAlgNameLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgNameLabel.setGeometry(QtCore.QRect(1, 70, 111, 18))
        self.newAlgNameLabel.setObjectName("newAlgNameLabel")
        self.newAlgNameLineEdit = QtGui.QLineEdit(self.newAlgPropGroupBox)
        self.newAlgNameLineEdit.setGeometry(QtCore.QRect(0, 90, 191, 26))
        self.newAlgNameLineEdit.setObjectName("newAlgNameLineEdit")
        self.newAlgTypeLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgTypeLabel.setGeometry(QtCore.QRect(2, 130, 111, 18))
        self.newAlgTypeLabel.setObjectName("newAlgTypeLabel")
        self.newAlgTypeComboBox = QtGui.QComboBox(self.newAlgPropGroupBox)
        self.newAlgTypeComboBox.setGeometry(QtCore.QRect(0, 150, 191, 27))
        self.newAlgTypeComboBox.setObjectName("newAlgTypeComboBox")
        self.newAlgArgsLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgArgsLabel.setGeometry(QtCore.QRect(2, 190, 141, 18))
        self.newAlgArgsLabel.setObjectName("newAlgArgsLabel")
        self.newAlgAddButton = QtGui.QPushButton(self.newAlgPropGroupBox)
        self.newAlgAddButton.setGeometry(QtCore.QRect(70, 420, 51, 28))
        self.newAlgAddButton.setObjectName("newAlgAddButton")
        self.newAlgCancelButton = QtGui.QPushButton(self.newAlgPropGroupBox)
        self.newAlgCancelButton.setGeometry(QtCore.QRect(0, 420, 61, 28))
        self.newAlgCancelButton.setObjectName("newAlgCancelButton")
        self.newAlgArgsListView1 = QtGui.QListView(self.newAlgPropGroupBox)
        self.newAlgArgsListView1.setGeometry(QtCore.QRect(0, 210, 111, 181))
        self.newAlgArgsListView1.setObjectName("newAlgArgsListView1")
        self.newAlgArgsListView2 = QtGui.QListView(self.newAlgPropGroupBox)
        self.newAlgArgsListView2.setGeometry(QtCore.QRect(139, 210, 111, 111))
        self.newAlgArgsListView2.setObjectName("newAlgArgsListView2")
        self.newAlgAddArgButton = QtGui.QPushButton(self.newAlgPropGroupBox)
        self.newAlgAddArgButton.setGeometry(QtCore.QRect(112, 230, 26, 26))
        self.newAlgAddArgButton.setObjectName("newAlgAddArgButton")
        self.newAlgArgOpGroupBox = QtGui.QGroupBox(self.newAlgPropGroupBox)
        self.newAlgArgOpGroupBox.setGeometry(QtCore.QRect(139, 322, 111, 31))
        self.newAlgArgOpGroupBox.setObjectName("newAlgArgOpGroupBox")
        self.newAlgArgUpButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgUpButton.setGeometry(QtCore.QRect(8, 1, 26, 26))
        self.newAlgArgUpButton.setObjectName("newAlgArgUpButton")
        self.newAlgArgDownButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgDownButton.setGeometry(QtCore.QRect(37, 1, 26, 26))
        self.newAlgArgDownButton.setObjectName("newAlgArgDownButton")
        self.newAlgArgDelButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgDelButton.setGeometry(QtCore.QRect(75, 1, 26, 26))
        self.newAlgArgDelButton.setObjectName("newAlgArgDelButton")
        self.verticalLayout.addWidget(self.frame_2)
        self.newAlgDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.newAlgDockWidget)
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setMenuRole(QtGui.QAction.AboutRole)
        self.aboutAction.setObjectName("aboutAction")
        self.helpAction = QtGui.QAction(MainWindow)
        self.helpAction.setObjectName("helpAction")
        self.newAction = QtGui.QAction(MainWindow)
        self.newAction.setObjectName("newAction")
        self.quitAction = QtGui.QAction(MainWindow)
        self.quitAction.setMenuRole(QtGui.QAction.QuitRole)
        self.quitAction.setObjectName("quitAction")
        self.menuOptions.addAction(self.newAction)
        self.menuOptions.addAction(self.quitAction)
        self.menuHelp.addAction(self.helpAction)
        self.menuHelp.addAction(self.aboutAction)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.algDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Algorithms", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.algTree.isSortingEnabled()
        self.algTree.setSortingEnabled(False)
        self.algTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Sorting Algorithms", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Insertion Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Quick Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.setSortingEnabled(__sortingEnabled)
        self.algOptionsDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "List to sort", None, QtGui.QApplication.UnicodeUTF8))
        self.listSettingsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "List Generator Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.listLBoundLabel.setText(QtGui.QApplication.translate("MainWindow", "lower bound", None, QtGui.QApplication.UnicodeUTF8))
        self.listUBoundLabel.setText(QtGui.QApplication.translate("MainWindow", "upper bound", None, QtGui.QApplication.UnicodeUTF8))
        self.listSortButton.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.listInputRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Give List", None, QtGui.QApplication.UnicodeUTF8))
        self.listGenRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Generate List", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "New Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.pathLabel.setText(QtGui.QApplication.translate("MainWindow", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pathBrowseButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgFuncLabel.setText(QtGui.QApplication.translate("MainWindow", "Select function/algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Algorithm name:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Algorithm type:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgsLabel.setText(QtGui.QApplication.translate("MainWindow", "Function arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgCancelButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddArgButton.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgUpButton.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgDownButton.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgDelButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setText(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
