# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyAlgGui.ui'
#
# Created: Sat May 22 16:14:53 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 667)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_3.addWidget(self.webView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 25))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuPreferences = QtGui.QMenu(self.menuOptions)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuTrace_Plot_Type = QtGui.QMenu(self.menuPreferences)
        self.menuTrace_Plot_Type.setObjectName("menuTrace_Plot_Type")
        self.menuArguments_Input = QtGui.QMenu(self.menuPreferences)
        self.menuArguments_Input.setObjectName("menuArguments_Input")
        self.menuBenchmark_Wizard = QtGui.QMenu(self.menuPreferences)
        self.menuBenchmark_Wizard.setObjectName("menuBenchmark_Wizard")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.algDockWidget = QtGui.QDockWidget(MainWindow)
        self.algDockWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algDockWidget.sizePolicy().hasHeightForWidth())
        self.algDockWidget.setSizePolicy(sizePolicy)
        self.algDockWidget.setFloating(False)
        self.algDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.algDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.algDockWidget.setObjectName("algDockWidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algTree = QtGui.QTreeWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algTree.sizePolicy().hasHeightForWidth())
        self.algTree.setSizePolicy(sizePolicy)
        self.algTree.setObjectName("algTree")
        item_0 = QtGui.QTreeWidgetItem(self.algTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.algTree.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.algTree)
        self.algDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.algDockWidget)
        self.algOptionsDockWidget = QtGui.QDockWidget(MainWindow)
        self.algOptionsDockWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algOptionsDockWidget.sizePolicy().hasHeightForWidth())
        self.algOptionsDockWidget.setSizePolicy(sizePolicy)
        self.algOptionsDockWidget.setMinimumSize(QtCore.QSize(274, 248))
        self.algOptionsDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.algOptionsDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.algOptionsDockWidget.setObjectName("algOptionsDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setBaseSize(QtCore.QSize(0, 230))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.argumentsTabWidget = QtGui.QTabWidget(self.frame)
        self.argumentsTabWidget.setObjectName("argumentsTabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.argumentsTabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.argumentsTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.argumentsTabWidget)
        self.verticalLayout_4.addWidget(self.frame)
        self.runTracerButton = QtGui.QPushButton(self.dockWidgetContents)
        self.runTracerButton.setObjectName("runTracerButton")
        self.verticalLayout_4.addWidget(self.runTracerButton)
        self.algOptionsDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.algOptionsDockWidget)
        self.newAlgDockWidget = QtGui.QDockWidget(MainWindow)
        self.newAlgDockWidget.setMinimumSize(QtCore.QSize(250, 619))
        self.newAlgDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.newAlgDockWidget.setObjectName("newAlgDockWidget")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents_3)
        self.frame_2.setMinimumSize(QtCore.QSize(232, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pathLabel = QtGui.QLabel(self.frame_2)
        self.pathLabel.setGeometry(QtCore.QRect(10, 10, 61, 18))
        self.pathLabel.setObjectName("pathLabel")
        self.pathLineEdit = QtGui.QLineEdit(self.frame_2)
        self.pathLineEdit.setGeometry(QtCore.QRect(10, 30, 161, 26))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.pathBrowseButton = QtGui.QPushButton(self.frame_2)
        self.pathBrowseButton.setGeometry(QtCore.QRect(175, 30, 26, 26))
        self.pathBrowseButton.setObjectName("pathBrowseButton")
        self.newAlgPropGroupBox = QtGui.QGroupBox(self.frame_2)
        self.newAlgPropGroupBox.setGeometry(QtCore.QRect(10, 60, 211, 501))
        self.newAlgPropGroupBox.setObjectName("newAlgPropGroupBox")
        self.newAlgFuncLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgFuncLabel.setGeometry(QtCore.QRect(0, 10, 201, 18))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.newAlgFuncLabel.setFont(font)
        self.newAlgFuncLabel.setObjectName("newAlgFuncLabel")
        self.newAlgFuncComboBox = QtGui.QComboBox(self.newAlgPropGroupBox)
        self.newAlgFuncComboBox.setGeometry(QtCore.QRect(0, 33, 191, 27))
        self.newAlgFuncComboBox.setObjectName("newAlgFuncComboBox")
        self.newAlgNameLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgNameLabel.setGeometry(QtCore.QRect(1, 75, 141, 18))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.newAlgNameLabel.setFont(font)
        self.newAlgNameLabel.setObjectName("newAlgNameLabel")
        self.newAlgNameLineEdit = QtGui.QLineEdit(self.newAlgPropGroupBox)
        self.newAlgNameLineEdit.setGeometry(QtCore.QRect(0, 98, 191, 26))
        self.newAlgNameLineEdit.setObjectName("newAlgNameLineEdit")
        self.newAlgTypeLabel = QtGui.QLabel(self.newAlgPropGroupBox)
        self.newAlgTypeLabel.setGeometry(QtCore.QRect(2, 133, 121, 18))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.newAlgTypeLabel.setFont(font)
        self.newAlgTypeLabel.setObjectName("newAlgTypeLabel")
        self.newAlgTypeComboBox = QtGui.QComboBox(self.newAlgPropGroupBox)
        self.newAlgTypeComboBox.setGeometry(QtCore.QRect(0, 153, 191, 27))
        self.newAlgTypeComboBox.setObjectName("newAlgTypeComboBox")
        self.groupBox = QtGui.QGroupBox(self.newAlgPropGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(0, 200, 201, 251))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.newAlgAddArgLabel = QtGui.QLabel(self.groupBox)
        self.newAlgAddArgLabel.setGeometry(QtCore.QRect(0, 23, 201, 41))
        self.newAlgAddArgLabel.setScaledContents(False)
        self.newAlgAddArgLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.newAlgAddArgLabel.setWordWrap(True)
        self.newAlgAddArgLabel.setObjectName("newAlgAddArgLabel")
        self.newAlgArgsListView1 = QtGui.QListView(self.groupBox)
        self.newAlgArgsListView1.setGeometry(QtCore.QRect(0, 110, 81, 121))
        self.newAlgArgsListView1.setObjectName("newAlgArgsListView1")
        self.newAlgArgsLabel1 = QtGui.QLabel(self.groupBox)
        self.newAlgArgsLabel1.setGeometry(QtCore.QRect(0, 70, 81, 31))
        self.newAlgArgsLabel1.setWordWrap(True)
        self.newAlgArgsLabel1.setObjectName("newAlgArgsLabel1")
        self.newAlgArgsListView2 = QtGui.QListView(self.groupBox)
        self.newAlgArgsListView2.setGeometry(QtCore.QRect(120, 110, 81, 91))
        self.newAlgArgsListView2.setObjectName("newAlgArgsListView2")
        self.newAlgArgsLabel2 = QtGui.QLabel(self.groupBox)
        self.newAlgArgsLabel2.setGeometry(QtCore.QRect(121, 70, 81, 31))
        self.newAlgArgsLabel2.setWordWrap(True)
        self.newAlgArgsLabel2.setObjectName("newAlgArgsLabel2")
        self.newAlgAddArgButton = QtGui.QPushButton(self.groupBox)
        self.newAlgAddArgButton.setGeometry(QtCore.QRect(90, 110, 26, 26))
        self.newAlgAddArgButton.setObjectName("newAlgAddArgButton")
        self.newAlgArgOpGroupBox = QtGui.QGroupBox(self.groupBox)
        self.newAlgArgOpGroupBox.setGeometry(QtCore.QRect(110, 200, 91, 31))
        self.newAlgArgOpGroupBox.setObjectName("newAlgArgOpGroupBox")
        self.newAlgArgUpButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgUpButton.setGeometry(QtCore.QRect(10, 4, 26, 26))
        self.newAlgArgUpButton.setObjectName("newAlgArgUpButton")
        self.newAlgArgDownButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgDownButton.setGeometry(QtCore.QRect(38, 4, 26, 26))
        self.newAlgArgDownButton.setObjectName("newAlgArgDownButton")
        self.newAlgArgDelButton = QtGui.QPushButton(self.newAlgArgOpGroupBox)
        self.newAlgArgDelButton.setGeometry(QtCore.QRect(66, 4, 26, 26))
        self.newAlgArgDelButton.setObjectName("newAlgArgDelButton")
        self.newAlgArgsLabel0 = QtGui.QLabel(self.groupBox)
        self.newAlgArgsLabel0.setGeometry(QtCore.QRect(0, 0, 191, 18))
        self.newAlgArgsLabel0.setObjectName("newAlgArgsLabel0")
        self.newAlgAddButton = QtGui.QPushButton(self.newAlgPropGroupBox)
        self.newAlgAddButton.setGeometry(QtCore.QRect(70, 460, 51, 28))
        self.newAlgAddButton.setObjectName("newAlgAddButton")
        self.newAlgCancelButton = QtGui.QPushButton(self.newAlgPropGroupBox)
        self.newAlgCancelButton.setGeometry(QtCore.QRect(3, 460, 61, 28))
        self.newAlgCancelButton.setObjectName("newAlgCancelButton")
        self.verticalLayout.addWidget(self.frame_2)
        self.newAlgDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.newAlgDockWidget)
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setMenuRole(QtGui.QAction.AboutRole)
        self.aboutAction.setObjectName("aboutAction")
        self.helpAction = QtGui.QAction(MainWindow)
        self.helpAction.setObjectName("helpAction")
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.quitAction = QtGui.QAction(MainWindow)
        self.quitAction.setMenuRole(QtGui.QAction.QuitRole)
        self.quitAction.setObjectName("quitAction")
        self.deleteAction = QtGui.QAction(MainWindow)
        self.deleteAction.setObjectName("deleteAction")
        self.newAction = QtGui.QAction(MainWindow)
        self.newAction.setObjectName("newAction")
        self.renameAction = QtGui.QAction(MainWindow)
        self.renameAction.setObjectName("renameAction")
        self.argumentsAction = QtGui.QAction(MainWindow)
        self.argumentsAction.setObjectName("argumentsAction")
        self.compareAction = QtGui.QAction(MainWindow)
        self.compareAction.setObjectName("compareAction")
        self.compAction = QtGui.QAction(MainWindow)
        self.compAction.setObjectName("compAction")
        self.linePlotAction = QtGui.QAction(MainWindow)
        self.linePlotAction.setCheckable(True)
        self.linePlotAction.setObjectName("linePlotAction")
        self.barPlotAction = QtGui.QAction(MainWindow)
        self.barPlotAction.setCheckable(True)
        self.barPlotAction.setObjectName("barPlotAction")
        self.filledBarPlotAction = QtGui.QAction(MainWindow)
        self.filledBarPlotAction.setCheckable(True)
        self.filledBarPlotAction.setObjectName("filledBarPlotAction")
        self.manualArgsAction = QtGui.QAction(MainWindow)
        self.manualArgsAction.setCheckable(True)
        self.manualArgsAction.setObjectName("manualArgsAction")
        self.autoArgsAction = QtGui.QAction(MainWindow)
        self.autoArgsAction.setCheckable(True)
        self.autoArgsAction.setObjectName("autoArgsAction")
        self.savePreferencesAction = QtGui.QAction(MainWindow)
        self.savePreferencesAction.setObjectName("savePreferencesAction")
        self.websiteAction = QtGui.QAction(MainWindow)
        self.websiteAction.setObjectName("websiteAction")
        self.keyShortcutsAction = QtGui.QAction(MainWindow)
        self.keyShortcutsAction.setObjectName("keyShortcutsAction")
        self.saveAction = QtGui.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.nrBenchExecAction = QtGui.QAction(MainWindow)
        self.nrBenchExecAction.setObjectName("nrBenchExecAction")
        self.actionW = QtGui.QAction(MainWindow)
        self.actionW.setObjectName("actionW")
        self.menuTrace_Plot_Type.addAction(self.linePlotAction)
        self.menuTrace_Plot_Type.addAction(self.barPlotAction)
        self.menuTrace_Plot_Type.addAction(self.filledBarPlotAction)
        self.menuArguments_Input.addAction(self.manualArgsAction)
        self.menuArguments_Input.addAction(self.autoArgsAction)
        self.menuBenchmark_Wizard.addAction(self.nrBenchExecAction)
        self.menuPreferences.addAction(self.menuArguments_Input.menuAction())
        self.menuPreferences.addAction(self.menuTrace_Plot_Type.menuAction())
        self.menuPreferences.addAction(self.menuBenchmark_Wizard.menuAction())
        self.menuOptions.addAction(self.newAction)
        self.menuOptions.addAction(self.saveAction)
        self.menuOptions.addAction(self.menuPreferences.menuAction())
        self.menuOptions.addAction(self.quitAction)
        self.menuHelp.addAction(self.helpAction)
        self.menuHelp.addAction(self.websiteAction)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.aboutAction)
        self.menuEdit.addAction(self.renameAction)
        self.menuEdit.addAction(self.argumentsAction)
        self.menuEdit.addAction(self.deleteAction)
        self.menuTools.addAction(self.compAction)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.argumentsTabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyAlgLib", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferences.setTitle(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTrace_Plot_Type.setTitle(QtGui.QApplication.translate("MainWindow", "Trace Plot Type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArguments_Input.setTitle(QtGui.QApplication.translate("MainWindow", "Arguments Input", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBenchmark_Wizard.setTitle(QtGui.QApplication.translate("MainWindow", "Benchmark Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.algDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Algorithm Library", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.algTree.isSortingEnabled()
        self.algTree.setSortingEnabled(False)
        self.algTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Sorting Algorithms", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Insertion Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Quick Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.algTree.setSortingEnabled(__sortingEnabled)
        self.algOptionsDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.argumentsTabWidget.setTabText(self.argumentsTabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.argumentsTabWidget.setTabText(self.argumentsTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.runTracerButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "New Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.pathLabel.setText(QtGui.QApplication.translate("MainWindow", "File path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pathBrowseButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgFuncLabel.setText(QtGui.QApplication.translate("MainWindow", "Select function/algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Algorithm name:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Algorithm type:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddArgLabel.setText(QtGui.QApplication.translate("MainWindow", "Add the function arguments (respecting type and order).", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgsLabel1.setText(QtGui.QApplication.translate("MainWindow", "Available arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgsLabel2.setText(QtGui.QApplication.translate("MainWindow", "Function arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddArgButton.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgUpButton.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgDownButton.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgDelButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgArgsLabel0.setText(QtGui.QApplication.translate("MainWindow", "Algorithm arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add algorithm to library", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgCancelButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Abort adding algorithm to library", None, QtGui.QApplication.UnicodeUTF8))
        self.newAlgCancelButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAction.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setText(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.renameAction.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.renameAction.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.argumentsAction.setText(QtGui.QApplication.translate("MainWindow", "Arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.compareAction.setText(QtGui.QApplication.translate("MainWindow", "Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.compAction.setText(QtGui.QApplication.translate("MainWindow", "Benchmarking", None, QtGui.QApplication.UnicodeUTF8))
        self.linePlotAction.setText(QtGui.QApplication.translate("MainWindow", "Line Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.barPlotAction.setText(QtGui.QApplication.translate("MainWindow", "Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.filledBarPlotAction.setText(QtGui.QApplication.translate("MainWindow", "Bar (filled)", None, QtGui.QApplication.UnicodeUTF8))
        self.manualArgsAction.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.autoArgsAction.setText(QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.savePreferencesAction.setText(QtGui.QApplication.translate("MainWindow", "Save Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.websiteAction.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.keyShortcutsAction.setText(QtGui.QApplication.translate("MainWindow", "Keyboard Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.nrBenchExecAction.setText(QtGui.QApplication.translate("MainWindow", "Number executions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionW.setText(QtGui.QApplication.translate("MainWindow", "w", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
